#!/usr/bin/env python3
"""Root command-line entry for the SNL compiler project."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from src.snl_codegen import CodegenError, compile_source
from src.snl_lexer import DEFAULT_GRAMMAR, SNLLexer, format_text, load_grammar
from src.snl_parser import SNLParser, format_parse_result, load_tokens
from src.snl_semantic import SNLSemanticAnalyzer, format_semantic_result
from src.snl_visualize import visualize_source
from src.snl_web import serve_web


def default_out_dir(source: Path, kind: str) -> Path:
    return PROJECT_ROOT / "test" / "out" / f"{kind}_{source.stem}"


def command_lex(args: argparse.Namespace) -> int:
    tokens = SNLLexer(load_grammar(args.grammar)).tokenize(
        args.source.read_text(encoding="utf-8"),
        include_eof=args.with_eof,
    )
    text = format_text(tokens)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)
    return 0


def command_parse(args: argparse.Namespace) -> int:
    tokens = load_tokens(args.tokens)
    parser = SNLParser(tokens)
    tree = parser.parse()
    text = format_parse_result(parser.errors, tree)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)
    return 0


def command_semantic(args: argparse.Namespace) -> int:
    tokens = load_tokens(args.tokens)
    analyzer = SNLSemanticAnalyzer(tokens)
    analyzer.analyze()
    text = format_semantic_result(analyzer)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)
    return 0


def command_compile(args: argparse.Namespace) -> int:
    out_dir = args.out_dir or default_out_dir(args.source, "compile")
    assembly, result_text = compile_source(
        args.source,
        out_dir,
        list(args.input),
        run_target=not args.no_run,
        max_steps=args.max_steps,
    )
    if args.asm:
        args.asm.parent.mkdir(parents=True, exist_ok=True)
        args.asm.write_text(assembly, encoding="utf-8")
    print(result_text if not args.no_run else assembly)
    return 0


def command_visualize(args: argparse.Namespace) -> int:
    out_dir = args.out_dir or default_out_dir(args.source, "visual")
    generated = visualize_source(args.source, out_dir, list(args.input), max_steps=args.max_steps)
    print(f"Visualization index: {generated['Index']}")
    for label, path in generated.items():
        if label != "Index":
            print(f"{label}: {path}")
    return 0


def command_web(args: argparse.Namespace) -> int:
    serve_web(PROJECT_ROOT, args.host, args.port)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="SNL compiler entry point: lex, parse, analyze, compile, and visualize.",
    )
    subcommands = parser.add_subparsers(dest="command", required=True)

    lex = subcommands.add_parser("lex", help="run lexical analysis")
    lex.add_argument("source", type=Path, help="SNL source file")
    lex.add_argument("-g", "--grammar", type=Path, default=DEFAULT_GRAMMAR, help="lexical grammar file")
    lex.add_argument("-o", "--output", type=Path, help="write token sequence to this file")
    lex.add_argument("--with-eof", action="store_true", help="append EOF token")
    lex.set_defaults(func=command_lex)

    parse = subcommands.add_parser("parse", help="run recursive-descent syntax analysis")
    parse.add_argument("tokens", type=Path, help="token file generated by lex")
    parse.add_argument("-o", "--output", type=Path, help="write syntax report and tree")
    parse.set_defaults(func=command_parse)

    semantic = subcommands.add_parser("semantic", help="run semantic analysis")
    semantic.add_argument("tokens", type=Path, help="token file generated by lex")
    semantic.add_argument("-o", "--output", type=Path, help="write semantic report")
    semantic.set_defaults(func=command_semantic)

    compile_cmd = subcommands.add_parser("compile", help="compile SNL source to MIPS and run it")
    compile_cmd.add_argument("source", type=Path, help="SNL source file")
    compile_cmd.add_argument("--out-dir", type=Path, help="directory for tokens/tree/semantic/asm/result outputs")
    compile_cmd.add_argument("--input", nargs="*", default=[], help="input values consumed by READ")
    compile_cmd.add_argument("--asm", type=Path, help="also write assembly to this explicit path")
    compile_cmd.add_argument("--no-run", action="store_true", help="generate assembly without running MIPS")
    compile_cmd.add_argument("--max-steps", type=int, default=100000, help="maximum MIPS instructions to execute")
    compile_cmd.set_defaults(func=command_compile)

    visualize = subcommands.add_parser("visualize", help="generate compiler side-information visualizations")
    visualize.add_argument("source", type=Path, help="SNL source file")
    visualize.add_argument("--out-dir", type=Path, help="directory for HTML/SVG/JSON outputs")
    visualize.add_argument("--input", nargs="*", default=[], help="input values consumed by READ")
    visualize.add_argument("--max-steps", type=int, default=100000, help="maximum MIPS instructions to execute")
    visualize.set_defaults(func=command_visualize)

    web = subcommands.add_parser("web", help="run the local web playground")
    web.add_argument("--host", default="127.0.0.1", help="host to bind the web server")
    web.add_argument("--port", type=int, default=8000, help="port to bind the web server")
    web.set_defaults(func=command_web)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (OSError, CodegenError, json.JSONDecodeError, RuntimeError) as exc:
        print(f"compiler.py: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
