#!/usr/bin/env python3
"""Recursive-descent parser for SNL token sequences.

Input:  Token sequence generated by snl_lexer.py
Output: syntax error information and a hierarchical syntax tree
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path


EXPR_START = {"LPAREN", "INTC", "CHARC", "ID"}
TYPE_START = {"INTEGER", "CHAR", "ARRAY", "RECORD", "ID"}
FIELD_TYPE_START = {"INTEGER", "CHAR", "ARRAY"}
STMT_START = {"IF", "WHILE", "READ", "WRITE", "RETURN", "ID"}
STMT_END = {"END", "ELSE", "FI", "ENDWH", "EOF", "DOT"}
ADD_OPS = {"PLUS": "+", "MINUS": "-"}
MULT_OPS = {"TIMES": "*", "OVER": "/"}
CMP_OPS = {"LT": "<", "EQ": "="}


@dataclass(frozen=True)
class Token:
    line: int
    lex: str
    sem: str = ""

    def display(self) -> str:
        if self.sem:
            return f"{self.lex}({self.sem})"
        return self.lex


@dataclass
class TreeNode:
    kind: str
    value: str = ""
    children: list["TreeNode"] = field(default_factory=list)

    def add(self, child: "TreeNode | None") -> "TreeNode":
        if child is not None:
            self.children.append(child)
        return self

    def extend(self, children: list["TreeNode"]) -> "TreeNode":
        self.children.extend(children)
        return self

    def label(self) -> str:
        return f"{self.kind} {self.value}".rstrip()

    def format(self, indent: int = 0) -> list[str]:
        lines = [" " * indent + self.label()]
        for child in self.children:
            lines.extend(child.format(indent + 4))
        return lines


class ParserError(RuntimeError):
    pass


def load_tokens(path: Path) -> list[Token]:
    text = path.read_text(encoding="utf-8")
    stripped = text.lstrip()
    if stripped.startswith("["):
        data = json.loads(text)
        tokens = [
            Token(
                int(item.get("line_show", item.get("line", 0))),
                str(item["lex"]),
                str(item.get("sem", "")),
            )
            for item in data
        ]
    else:
        tokens = []
        for raw_line in text.splitlines():
            line = raw_line.strip()
            if not line or line.startswith("LineShow") or line.startswith("--------"):
                continue
            parts = line.split(maxsplit=2)
            if len(parts) < 2:
                continue
            try:
                line_show = int(parts[0])
            except ValueError:
                continue
            sem = parts[2].strip() if len(parts) == 3 else ""
            tokens.append(Token(line_show, parts[1], sem))

    if not tokens:
        raise ParserError(f"{path}: no tokens found")
    if tokens[-1].lex != "EOF":
        tokens.append(Token(tokens[-1].line, "EOF"))
    return tokens


class SNLParser:
    def __init__(self, tokens: list[Token]) -> None:
        self.tokens = tokens
        self.index = 0
        self.errors: list[str] = []

    @property
    def current(self) -> Token:
        if self.index < len(self.tokens):
            return self.tokens[self.index]
        return self.tokens[-1]

    def at(self, *lex_types: str) -> bool:
        return self.current.lex in lex_types

    def advance(self) -> Token:
        token = self.current
        if self.index < len(self.tokens) - 1:
            self.index += 1
        return token

    def expect(self, lex_type: str) -> Token:
        if self.current.lex == lex_type:
            return self.advance()
        token = self.current
        self.error(f"expected {lex_type}, found {token.display()}")
        return Token(token.line, lex_type)

    def error(self, message: str) -> None:
        self.errors.append(f"line {self.current.line}: {message}")

    def parse(self) -> TreeNode:
        root = self.parse_program()
        if not self.at("EOF"):
            self.error(f"unexpected token after program end: {self.current.display()}")
        return root

    def parse_program(self) -> TreeNode:
        root = TreeNode("ProK")
        root.add(self.parse_program_head())
        root.extend(self.parse_declare_part())
        root.add(self.parse_program_body())
        self.expect("DOT")
        return root

    def parse_program_head(self) -> TreeNode:
        self.expect("PROGRAM")
        name = self.expect("ID")
        return TreeNode("PheadK", name.sem)

    def parse_declare_part(self) -> list[TreeNode]:
        nodes: list[TreeNode] = []
        type_node = self.parse_type_dec()
        var_node = self.parse_var_dec()
        proc_nodes = self.parse_proc_dec()
        if type_node.children:
            nodes.append(type_node)
        if var_node.children:
            nodes.append(var_node)
        nodes.extend(proc_nodes)
        return nodes

    def parse_type_dec(self) -> TreeNode:
        node = TreeNode("TypeK")
        if not self.at("TYPE"):
            return node
        self.advance()
        while self.at("ID"):
            type_id = self.advance()
            self.expect("EQ")
            type_name = self.parse_type_name()
            self.expect("SEMI")
            node.add(TreeNode("DecK", type_id.sem).add(type_name))
        return node

    def parse_type_name(self) -> TreeNode:
        if self.at("INTEGER"):
            self.advance()
            return TreeNode("IntegerK")
        if self.at("CHAR"):
            self.advance()
            return TreeNode("CharK")
        if self.at("ARRAY"):
            return self.parse_array_type()
        if self.at("RECORD"):
            return self.parse_record_type()
        if self.at("ID"):
            token = self.advance()
            return TreeNode("IdTypeK", token.sem)

        self.error(f"expected type name, found {self.current.display()}")
        self.recover(TYPE_START | {"SEMI", "RPAREN", "BEGIN", "PROCEDURE", "EOF"})
        return TreeNode("ErrorTypeK")

    def parse_array_type(self) -> TreeNode:
        self.expect("ARRAY")
        self.expect("LMIDPAREN")
        low = self.expect("INTC")
        self.expect("UNDERANGE")
        top = self.expect("INTC")
        self.expect("RMIDPAREN")
        self.expect("OF")
        base = self.parse_base_type()
        return TreeNode("ArrayK", f"{low.sem}..{top.sem}").add(base)

    def parse_base_type(self) -> TreeNode:
        if self.at("INTEGER"):
            self.advance()
            return TreeNode("IntegerK")
        if self.at("CHAR"):
            self.advance()
            return TreeNode("CharK")
        self.error(f"expected base type INTEGER or CHAR, found {self.current.display()}")
        return TreeNode("ErrorTypeK")

    def parse_record_type(self) -> TreeNode:
        self.expect("RECORD")
        node = TreeNode("RecordK")
        while self.current.lex in FIELD_TYPE_START:
            node.add(self.parse_field_dec())
        self.expect("END")
        return node

    def parse_field_dec(self) -> TreeNode:
        if self.at("ARRAY"):
            type_node = self.parse_array_type()
        else:
            type_node = self.parse_base_type()
        ids = self.parse_id_list()
        self.expect("SEMI")
        return TreeNode("DecK", ", ".join(ids)).add(type_node)

    def parse_id_list(self) -> list[str]:
        ids = [self.expect("ID").sem]
        while self.at("COMMA"):
            self.advance()
            ids.append(self.expect("ID").sem)
        return ids

    def parse_var_dec(self) -> TreeNode:
        node = TreeNode("VarK")
        if not self.at("VAR"):
            return node
        self.advance()
        while self.current.lex in TYPE_START:
            type_node = self.parse_type_name()
            ids = self.parse_id_list()
            self.expect("SEMI")
            node.add(TreeNode("DecK", ", ".join(ids)).add(type_node))
        return node

    def parse_proc_dec(self) -> list[TreeNode]:
        procedures: list[TreeNode] = []
        while self.at("PROCEDURE"):
            procedures.append(self.parse_proc_declaration())
        return procedures

    def parse_proc_declaration(self) -> TreeNode:
        self.expect("PROCEDURE")
        name = self.expect("ID")
        node = TreeNode("ProcDecK", name.sem)
        self.expect("LPAREN")
        node.add(self.parse_param_list())
        self.expect("RPAREN")
        self.expect("SEMI")
        node.extend(self.parse_declare_part())
        node.add(self.parse_program_body())
        return node

    def parse_param_list(self) -> TreeNode:
        node = TreeNode("ParamListK")
        if self.at("RPAREN"):
            return node
        node.add(self.parse_param())
        while self.at("SEMI"):
            self.advance()
            node.add(self.parse_param())
        return node

    def parse_param(self) -> TreeNode:
        mode = "var" if self.at("VAR") else "value"
        if self.at("VAR"):
            self.advance()
        type_node = self.parse_type_name()
        ids = self.parse_id_list()
        return TreeNode("ParamK", f"{mode}: {', '.join(ids)}").add(type_node)

    def parse_program_body(self) -> TreeNode:
        self.expect("BEGIN")
        node = self.parse_stm_list({"END"})
        self.expect("END")
        return node

    def parse_stm_list(self, terminators: set[str]) -> TreeNode:
        node = TreeNode("StmLK")
        if self.current.lex in terminators:
            self.error("expected statement before statement-list terminator")
            return node

        while not self.at("EOF") and self.current.lex not in terminators:
            if self.current.lex in STMT_START:
                node.add(self.parse_stm())
                if self.at("SEMI"):
                    self.advance()
                    continue
                if self.current.lex in terminators:
                    break
                if self.current.lex in STMT_START:
                    self.error("missing SEMI between statements")
                    continue
                self.error(f"expected SEMI or terminator, found {self.current.display()}")
                self.recover(STMT_START | terminators | {"SEMI"})
                if self.at("SEMI"):
                    self.advance()
                continue

            self.error(f"expected statement, found {self.current.display()}")
            self.recover(STMT_START | terminators | {"SEMI"})
            if self.at("SEMI"):
                self.advance()

        return node

    def parse_stm(self) -> TreeNode:
        if self.at("IF"):
            return self.parse_conditional_stm()
        if self.at("WHILE"):
            return self.parse_loop_stm()
        if self.at("READ"):
            return self.parse_input_stm()
        if self.at("WRITE"):
            return self.parse_output_stm()
        if self.at("RETURN"):
            return self.parse_return_stm()
        if self.at("ID"):
            name = self.advance()
            if self.at("LPAREN"):
                return self.parse_call_stm_rest(name)
            return self.parse_assignment_rest(name)

        self.error(f"expected statement, found {self.current.display()}")
        self.advance()
        return TreeNode("StmtK", "Error")

    def parse_assignment_rest(self, name: Token) -> TreeNode:
        variable = self.finish_variable(name)
        self.expect("ASSIGN")
        expr = self.parse_exp()
        return TreeNode("StmtK", "Assign").add(variable).add(expr)

    def parse_call_stm_rest(self, name: Token) -> TreeNode:
        node = TreeNode("StmtK", "Call").add(TreeNode("ExpK", f"{name.sem} IdV"))
        self.expect("LPAREN")
        if not self.at("RPAREN"):
            for arg in self.parse_act_param_list():
                node.add(arg)
        self.expect("RPAREN")
        return node

    def parse_conditional_stm(self) -> TreeNode:
        self.expect("IF")
        node = TreeNode("StmtK", "If")
        node.add(self.parse_rel_exp())
        self.expect("THEN")
        node.add(self.parse_stm_list({"ELSE"}))
        self.expect("ELSE")
        node.add(self.parse_stm_list({"FI"}))
        self.expect("FI")
        return node

    def parse_loop_stm(self) -> TreeNode:
        self.expect("WHILE")
        node = TreeNode("StmtK", "While")
        node.add(self.parse_rel_exp())
        self.expect("DO")
        node.add(self.parse_stm_list({"ENDWH"}))
        self.expect("ENDWH")
        return node

    def parse_input_stm(self) -> TreeNode:
        self.expect("READ")
        self.expect("LPAREN")
        name = self.expect("ID")
        self.expect("RPAREN")
        return TreeNode("StmtK", f"Read {name.sem}")

    def parse_output_stm(self) -> TreeNode:
        self.expect("WRITE")
        self.expect("LPAREN")
        expr = self.parse_exp()
        self.expect("RPAREN")
        return TreeNode("StmtK", "Write").add(expr)

    def parse_return_stm(self) -> TreeNode:
        self.expect("RETURN")
        self.expect("LPAREN")
        expr = self.parse_exp()
        self.expect("RPAREN")
        return TreeNode("StmtK", "Return").add(expr)

    def parse_act_param_list(self) -> list[TreeNode]:
        params = [self.parse_exp()]
        while self.at("COMMA"):
            self.advance()
            params.append(self.parse_exp())
        return params

    def parse_rel_exp(self) -> TreeNode:
        left = self.parse_exp()
        if self.current.lex in CMP_OPS:
            op = CMP_OPS[self.advance().lex]
            right = self.parse_exp()
            return TreeNode("ExpK", f"Op {op}").add(left).add(right)
        self.error(f"expected comparison operator, found {self.current.display()}")
        return left

    def parse_exp(self) -> TreeNode:
        left = self.parse_term()
        if self.current.lex in ADD_OPS:
            op = ADD_OPS[self.advance().lex]
            right = self.parse_exp()
            return TreeNode("ExpK", f"Op {op}").add(left).add(right)
        return left

    def parse_term(self) -> TreeNode:
        left = self.parse_factor()
        if self.current.lex in MULT_OPS:
            op = MULT_OPS[self.advance().lex]
            right = self.parse_term()
            return TreeNode("ExpK", f"Op {op}").add(left).add(right)
        return left

    def parse_factor(self) -> TreeNode:
        if self.at("LPAREN"):
            self.advance()
            expr = self.parse_exp()
            self.expect("RPAREN")
            return expr
        if self.at("INTC"):
            token = self.advance()
            return TreeNode("ExpK", f"Const {token.sem}")
        if self.at("CHARC"):
            token = self.advance()
            return TreeNode("ExpK", f"Char {token.sem}")
        if self.at("ID"):
            return self.finish_variable(self.advance())

        self.error(f"expected expression factor, found {self.current.display()}")
        if not self.at("EOF"):
            self.advance()
        return TreeNode("ExpK", "Error")

    def finish_variable(self, name: Token) -> TreeNode:
        node = TreeNode("ExpK", f"{name.sem} IdV")
        if self.at("LMIDPAREN"):
            self.advance()
            node.add(TreeNode("IndexK").add(self.parse_exp()))
            self.expect("RMIDPAREN")
        elif self.at("DOT"):
            self.advance()
            field = self.expect("ID")
            field_node = TreeNode("FieldK", field.sem)
            if self.at("LMIDPAREN"):
                self.advance()
                field_node.add(TreeNode("IndexK").add(self.parse_exp()))
                self.expect("RMIDPAREN")
            node.add(field_node)
        return node

    def recover(self, stop_set: set[str]) -> None:
        while not self.at("EOF") and self.current.lex not in stop_set:
            self.advance()


def format_parse_result(errors: list[str], root: TreeNode) -> str:
    lines = ["Syntax Errors"]
    if errors:
        lines.extend(errors)
    else:
        lines.append("No syntax errors.")
    lines.append("")
    lines.append("Syntax Tree")
    lines.extend(root.format())
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Parse an SNL token sequence and output syntax errors plus a syntax tree."
    )
    parser.add_argument("tokens", type=Path, help="token file generated by snl_lexer.py")
    parser.add_argument("-o", "--output", type=Path, help="write parse result to this file")
    args = parser.parse_args(argv)

    try:
        tokens = load_tokens(args.tokens)
        snl_parser = SNLParser(tokens)
        tree = snl_parser.parse()
        output = format_parse_result(snl_parser.errors, tree)
    except (OSError, ParserError, json.JSONDecodeError) as exc:
        print(f"snl_parser.py: {exc}", file=sys.stderr)
        return 2

    if args.output:
        args.output.write_text(output + "\n", encoding="utf-8")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
