#!/usr/bin/env python3
"""Semantic analyzer for the SNL teaching language.

Input:  Token sequence generated by snl_lexer.py
Output: semantic error information and symbol tables
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    from playground.snlcompiler.src.snl_parser import Token, load_tokens
except ModuleNotFoundError:
    from snl_parser import Token, load_tokens


TYPE_START = {"INTEGER", "CHAR", "ARRAY", "RECORD", "ID"}
FIELD_TYPE_START = {"INTEGER", "CHAR", "ARRAY"}
STMT_START = {"IF", "WHILE", "READ", "WRITE", "RETURN", "ID"}
ADD_OPS = {"PLUS": "+", "MINUS": "-"}
MULT_OPS = {"TIMES": "*", "OVER": "/"}
CMP_OPS = {"LT": "<", "EQ": "="}


@dataclass
class TypeInfo:
    kind: str
    low: int | None = None
    high: int | None = None
    element: "TypeInfo | None" = None
    fields: dict[str, "TypeInfo"] = field(default_factory=dict)

    def display(self) -> str:
        if self.kind == "array":
            element = self.element.display() if self.element else "unknown"
            return f"array[{self.low}..{self.high}] of {element}"
        if self.kind == "record":
            if not self.fields:
                return "record{}"
            fields = ", ".join(f"{name}: {typ.display()}" for name, typ in self.fields.items())
            return f"record{{{fields}}}"
        return self.kind


INTEGER = TypeInfo("integer")
CHAR = TypeInfo("char")
BOOL = TypeInfo("bool")
UNKNOWN = TypeInfo("unknown")
PROCEDURE_TYPE = TypeInfo("procedure")


@dataclass
class ParamInfo:
    name: str
    mode: str
    type_info: TypeInfo
    line: int

    def display(self) -> str:
        return f"{self.mode} {self.name}: {self.type_info.display()}"


@dataclass
class Symbol:
    name: str
    kind: str
    type_info: TypeInfo
    line: int
    params: list[ParamInfo] = field(default_factory=list)
    mode: str = ""

    def type_display(self) -> str:
        if self.kind == "procedure":
            params = ", ".join(param.display() for param in self.params)
            return f"procedure({params})"
        return self.type_info.display()

    def other_display(self) -> str:
        if self.kind == "param":
            return f"mode={self.mode}"
        if self.kind == "procedure":
            return f"params={len(self.params)}"
        return ""


@dataclass
class Scope:
    number: int
    name: str
    level: int
    parent: int | None
    symbols: dict[str, Symbol] = field(default_factory=dict)


@dataclass
class ExprInfo:
    type_info: TypeInfo = UNKNOWN
    assignable: bool = False
    const_int: int | None = None
    name: str = ""


class SemanticError(RuntimeError):
    pass


class SymbolTable:
    def __init__(self) -> None:
        self.scopes: list[Scope] = []
        self.stack: list[Scope] = []

    def enter(self, name: str) -> Scope:
        parent = self.stack[-1].number if self.stack else None
        scope = Scope(len(self.scopes), name, len(self.stack), parent)
        self.scopes.append(scope)
        self.stack.append(scope)
        return scope

    def leave(self) -> None:
        if self.stack:
            self.stack.pop()

    @property
    def current(self) -> Scope:
        return self.stack[-1]

    def declare(self, symbol: Symbol) -> Symbol | None:
        scope = self.current
        if symbol.name in scope.symbols:
            return scope.symbols[symbol.name]
        scope.symbols[symbol.name] = symbol
        return None

    def lookup(self, name: str) -> Symbol | None:
        for scope in reversed(self.stack):
            symbol = scope.symbols.get(name)
            if symbol is not None:
                return symbol
        return None


class SNLSemanticAnalyzer:
    def __init__(self, tokens: list[Token]) -> None:
        self.tokens = tokens
        self.index = 0
        self.errors: list[str] = []
        self.table = SymbolTable()

    @property
    def current(self) -> Token:
        if self.index < len(self.tokens):
            return self.tokens[self.index]
        return self.tokens[-1]

    def at(self, *lex_types: str) -> bool:
        return self.current.lex in lex_types

    def advance(self) -> Token:
        token = self.current
        if self.index < len(self.tokens) - 1:
            self.index += 1
        return token

    def expect(self, lex_type: str) -> Token:
        if self.current.lex == lex_type:
            return self.advance()
        token = self.current
        self.errors.append(f"line {token.line}: syntax barrier: expected {lex_type}, found {token.display()}")
        return Token(token.line, lex_type)

    def analyze(self) -> None:
        self.table.enter("global")
        self.parse_program()
        self.table.leave()

    def parse_program(self) -> None:
        self.expect("PROGRAM")
        program_name = self.expect("ID")
        if program_name.sem:
            self.declare(Symbol(program_name.sem, "program", UNKNOWN, program_name.line))
        self.parse_declare_part()
        self.parse_program_body()
        self.expect("DOT")

    def parse_declare_part(self) -> None:
        self.parse_type_dec()
        self.parse_var_dec()
        self.parse_proc_dec()

    def parse_type_dec(self) -> None:
        if not self.at("TYPE"):
            return
        self.advance()
        while self.at("ID"):
            name = self.advance()
            self.expect("EQ")
            type_info = self.parse_type_name()
            self.expect("SEMI")
            self.declare(Symbol(name.sem, "type", type_info, name.line))

    def parse_type_name(self) -> TypeInfo:
        if self.at("INTEGER"):
            self.advance()
            return INTEGER
        if self.at("CHAR"):
            self.advance()
            return CHAR
        if self.at("ARRAY"):
            return self.parse_array_type()
        if self.at("RECORD"):
            return self.parse_record_type()
        if self.at("ID"):
            token = self.advance()
            symbol = self.table.lookup(token.sem)
            if symbol is None:
                self.error(token, f"undeclared type identifier '{token.sem}'")
                return UNKNOWN
            if symbol.kind != "type":
                self.error(token, f"identifier '{token.sem}' is {symbol.kind}, expected type identifier")
                return UNKNOWN
            return symbol.type_info

        token = self.current
        self.error(token, f"expected type name, found {token.display()}")
        return UNKNOWN

    def parse_array_type(self) -> TypeInfo:
        self.expect("ARRAY")
        self.expect("LMIDPAREN")
        low_token = self.expect("INTC")
        self.expect("UNDERANGE")
        high_token = self.expect("INTC")
        self.expect("RMIDPAREN")
        self.expect("OF")
        element_type = self.parse_base_type()

        low = self.to_int(low_token)
        high = self.to_int(high_token)
        if low is not None and high is not None and low > high:
            self.error(low_token, f"array lower bound {low} is greater than upper bound {high}")
        return TypeInfo("array", low, high, element_type)

    def parse_base_type(self) -> TypeInfo:
        if self.at("INTEGER"):
            self.advance()
            return INTEGER
        if self.at("CHAR"):
            self.advance()
            return CHAR
        token = self.current
        self.error(token, f"expected base type INTEGER or CHAR, found {token.display()}")
        return UNKNOWN

    def parse_record_type(self) -> TypeInfo:
        self.expect("RECORD")
        fields: dict[str, TypeInfo] = {}
        while self.current.lex in FIELD_TYPE_START:
            if self.at("ARRAY"):
                field_type = self.parse_array_type()
            else:
                field_type = self.parse_base_type()
            ids = self.parse_id_list()
            self.expect("SEMI")
            for name, line in ids:
                if name in fields:
                    self.errors.append(f"line {line}: duplicate field identifier '{name}' in record type")
                else:
                    fields[name] = field_type
        self.expect("END")
        return TypeInfo("record", fields=fields)

    def parse_id_list(self) -> list[tuple[str, int]]:
        token = self.expect("ID")
        ids = [(token.sem, token.line)]
        while self.at("COMMA"):
            self.advance()
            token = self.expect("ID")
            ids.append((token.sem, token.line))
        return ids

    def parse_var_dec(self) -> None:
        if not self.at("VAR"):
            return
        self.advance()
        while self.current.lex in TYPE_START:
            var_type = self.parse_type_name()
            ids = self.parse_id_list()
            self.expect("SEMI")
            for name, line in ids:
                self.declare(Symbol(name, "var", var_type, line))

    def parse_proc_dec(self) -> None:
        while self.at("PROCEDURE"):
            self.parse_proc_declaration()

    def parse_proc_declaration(self) -> None:
        self.expect("PROCEDURE")
        name = self.expect("ID")
        self.expect("LPAREN")
        params = self.parse_param_list()
        self.expect("RPAREN")
        proc_symbol = Symbol(name.sem, "procedure", PROCEDURE_TYPE, name.line, params=params)
        self.declare(proc_symbol)
        self.expect("SEMI")

        self.table.enter(f"procedure {name.sem}")
        for param in params:
            self.declare(Symbol(param.name, "param", param.type_info, param.line, mode=param.mode))
        self.parse_declare_part()
        self.parse_program_body()
        self.table.leave()

    def parse_param_list(self) -> list[ParamInfo]:
        params: list[ParamInfo] = []
        if self.at("RPAREN"):
            return params
        params.extend(self.parse_param())
        while self.at("SEMI"):
            self.advance()
            params.extend(self.parse_param())
        return params

    def parse_param(self) -> list[ParamInfo]:
        mode = "var" if self.at("VAR") else "value"
        if self.at("VAR"):
            self.advance()
        param_type = self.parse_type_name()
        ids = self.parse_id_list()
        return [ParamInfo(name, mode, param_type, line) for name, line in ids]

    def parse_program_body(self) -> None:
        self.expect("BEGIN")
        self.parse_stm_list({"END"})
        self.expect("END")

    def parse_stm_list(self, terminators: set[str]) -> None:
        while not self.at("EOF") and self.current.lex not in terminators:
            if self.current.lex in STMT_START:
                self.parse_stm()
                if self.at("SEMI"):
                    self.advance()
                continue
            self.error(self.current, f"unexpected token in statement list: {self.current.display()}")
            self.advance()

    def parse_stm(self) -> None:
        if self.at("IF"):
            self.parse_conditional_stm()
        elif self.at("WHILE"):
            self.parse_loop_stm()
        elif self.at("READ"):
            self.parse_input_stm()
        elif self.at("WRITE"):
            self.parse_output_stm()
        elif self.at("RETURN"):
            self.parse_return_stm()
        elif self.at("ID"):
            name = self.advance()
            if self.at("LPAREN"):
                self.parse_call_stm_rest(name)
            else:
                self.parse_assignment_rest(name)
        else:
            self.error(self.current, f"expected statement, found {self.current.display()}")
            self.advance()

    def parse_assignment_rest(self, name: Token) -> None:
        left = self.finish_variable(name, require_variable=True)
        self.expect("ASSIGN")
        right = self.parse_exp()
        if not left.assignable:
            self.error(name, f"left side of assignment is not an assignable variable '{name.sem}'")
        if not same_type(left.type_info, right.type_info):
            self.error(
                name,
                "assignment type mismatch: "
                f"left is {left.type_info.display()}, right is {right.type_info.display()}",
            )

    def parse_call_stm_rest(self, name: Token) -> None:
        symbol = self.table.lookup(name.sem)
        if symbol is None:
            self.error(name, f"undeclared procedure identifier '{name.sem}'")
            expected_params: list[ParamInfo] = []
        elif symbol.kind != "procedure":
            self.error(name, f"identifier '{name.sem}' is {symbol.kind}, expected procedure identifier")
            expected_params = []
        else:
            expected_params = symbol.params

        self.expect("LPAREN")
        actuals: list[ExprInfo] = []
        if not self.at("RPAREN"):
            actuals = self.parse_act_param_list()
        self.expect("RPAREN")

        if symbol is not None and symbol.kind == "procedure":
            self.check_actual_params(name, expected_params, actuals)

    def check_actual_params(self, proc_token: Token, params: list[ParamInfo], actuals: list[ExprInfo]) -> None:
        if len(params) != len(actuals):
            self.error(
                proc_token,
                f"procedure '{proc_token.sem}' expects {len(params)} argument(s), got {len(actuals)}",
            )

        for index, (formal, actual) in enumerate(zip(params, actuals), 1):
            if formal.mode == "var" and not actual.assignable:
                self.error(
                    proc_token,
                    f"argument {index} for var parameter '{formal.name}' must be an assignable variable",
                )
            if not same_type(formal.type_info, actual.type_info):
                self.error(
                    proc_token,
                    f"argument {index} type mismatch for parameter '{formal.name}': "
                    f"expected {formal.type_info.display()}, got {actual.type_info.display()}",
                )

    def parse_conditional_stm(self) -> None:
        token = self.expect("IF")
        condition = self.parse_rel_exp()
        if not same_type(condition.type_info, BOOL):
            self.error(token, "if condition must be bool")
        self.expect("THEN")
        self.parse_stm_list({"ELSE"})
        self.expect("ELSE")
        self.parse_stm_list({"FI"})
        self.expect("FI")

    def parse_loop_stm(self) -> None:
        token = self.expect("WHILE")
        condition = self.parse_rel_exp()
        if not same_type(condition.type_info, BOOL):
            self.error(token, "while condition must be bool")
        self.expect("DO")
        self.parse_stm_list({"ENDWH"})
        self.expect("ENDWH")

    def parse_input_stm(self) -> None:
        self.expect("READ")
        self.expect("LPAREN")
        name = self.expect("ID")
        symbol = self.table.lookup(name.sem)
        if symbol is None:
            self.error(name, f"undeclared identifier '{name.sem}' in read statement")
        elif symbol.kind not in {"var", "param"}:
            self.error(name, f"identifier '{name.sem}' is {symbol.kind}, expected variable in read statement")
        elif symbol.type_info.kind in {"array", "record"}:
            self.error(name, f"read target '{name.sem}' must be scalar, got {symbol.type_info.display()}")
        self.expect("RPAREN")

    def parse_output_stm(self) -> None:
        self.expect("WRITE")
        self.expect("LPAREN")
        self.parse_exp()
        self.expect("RPAREN")

    def parse_return_stm(self) -> None:
        self.expect("RETURN")
        self.expect("LPAREN")
        self.parse_exp()
        self.expect("RPAREN")

    def parse_act_param_list(self) -> list[ExprInfo]:
        actuals = [self.parse_exp()]
        while self.at("COMMA"):
            self.advance()
            actuals.append(self.parse_exp())
        return actuals

    def parse_rel_exp(self) -> ExprInfo:
        left = self.parse_exp()
        if self.current.lex in CMP_OPS:
            op_token = self.advance()
            right = self.parse_exp()
            if not same_type(left.type_info, right.type_info):
                self.error(
                    op_token,
                    f"comparison operands have incompatible types: "
                    f"{left.type_info.display()} and {right.type_info.display()}",
                )
            return ExprInfo(BOOL)
        self.error(self.current, f"expected comparison operator, found {self.current.display()}")
        return ExprInfo(UNKNOWN)

    def parse_exp(self) -> ExprInfo:
        left = self.parse_term()
        if self.current.lex in ADD_OPS:
            op = self.advance()
            right = self.parse_exp()
            return self.check_arithmetic(op, left, right)
        return left

    def parse_term(self) -> ExprInfo:
        left = self.parse_factor()
        if self.current.lex in MULT_OPS:
            op = self.advance()
            right = self.parse_term()
            return self.check_arithmetic(op, left, right)
        return left

    def parse_factor(self) -> ExprInfo:
        if self.at("LPAREN"):
            self.advance()
            expr = self.parse_exp()
            self.expect("RPAREN")
            return ExprInfo(expr.type_info, False, expr.const_int)
        if self.at("INTC"):
            token = self.advance()
            return ExprInfo(INTEGER, const_int=self.to_int(token))
        if self.at("CHARC"):
            token = self.advance()
            return ExprInfo(CHAR, const_int=None, name=token.sem)
        if self.at("ID"):
            return self.finish_variable(self.advance(), require_variable=False)

        self.error(self.current, f"expected expression factor, found {self.current.display()}")
        self.advance()
        return ExprInfo(UNKNOWN)

    def check_arithmetic(self, op: Token, left: ExprInfo, right: ExprInfo) -> ExprInfo:
        if left.type_info.kind != "unknown" and left.type_info.kind != "integer":
            self.error(op, f"left operand of '{ADD_OPS.get(op.lex, MULT_OPS.get(op.lex, op.lex))}' must be integer")
        if right.type_info.kind != "unknown" and right.type_info.kind != "integer":
            self.error(op, f"right operand of '{ADD_OPS.get(op.lex, MULT_OPS.get(op.lex, op.lex))}' must be integer")
        return ExprInfo(INTEGER)

    def finish_variable(self, name: Token, require_variable: bool) -> ExprInfo:
        symbol = self.table.lookup(name.sem)
        if symbol is None:
            self.error(name, f"undeclared identifier '{name.sem}'")
            base_type = UNKNOWN
            assignable = False
        elif symbol.kind not in {"var", "param"}:
            if require_variable:
                self.error(name, f"identifier '{name.sem}' is {symbol.kind}, expected variable identifier")
            base_type = symbol.type_info
            assignable = False
        else:
            base_type = symbol.type_info
            assignable = True

        result = ExprInfo(base_type, assignable=assignable, name=name.sem)

        if self.at("LMIDPAREN"):
            bracket = self.advance()
            index_expr = self.parse_exp()
            self.expect("RMIDPAREN")
            result = self.apply_array_index(name, bracket, result, index_expr)
        elif self.at("DOT"):
            dot = self.advance()
            field = self.expect("ID")
            result = self.apply_record_field(name, dot, result, field)
            if self.at("LMIDPAREN"):
                bracket = self.advance()
                index_expr = self.parse_exp()
                self.expect("RMIDPAREN")
                result = self.apply_array_index(field, bracket, result, index_expr)

        return result

    def apply_array_index(
        self,
        name: Token,
        bracket: Token,
        base: ExprInfo,
        index_expr: ExprInfo,
    ) -> ExprInfo:
        if index_expr.type_info.kind != "unknown" and index_expr.type_info.kind != "integer":
            self.error(bracket, f"array index for '{name.sem}' must be integer")
        if base.type_info.kind != "array":
            if base.type_info.kind != "unknown":
                self.error(bracket, f"identifier '{name.sem}' is not an array")
            return ExprInfo(UNKNOWN, assignable=False, name=base.name)
        if index_expr.const_int is not None and base.type_info.low is not None and base.type_info.high is not None:
            if index_expr.const_int < base.type_info.low or index_expr.const_int > base.type_info.high:
                self.error(
                    bracket,
                    f"array index {index_expr.const_int} out of bounds "
                    f"[{base.type_info.low}..{base.type_info.high}] for '{name.sem}'",
                )
        return ExprInfo(base.type_info.element or UNKNOWN, assignable=base.assignable, name=base.name)

    def apply_record_field(self, name: Token, dot: Token, base: ExprInfo, field: Token) -> ExprInfo:
        if base.type_info.kind != "record":
            if base.type_info.kind != "unknown":
                self.error(dot, f"identifier '{name.sem}' is not a record")
            return ExprInfo(UNKNOWN, assignable=False, name=base.name)
        field_type = base.type_info.fields.get(field.sem)
        if field_type is None:
            self.error(field, f"record '{name.sem}' has no field '{field.sem}'")
            return ExprInfo(UNKNOWN, assignable=False, name=base.name)
        return ExprInfo(field_type, assignable=base.assignable, name=f"{base.name}.{field.sem}")

    def declare(self, symbol: Symbol) -> None:
        duplicate = self.table.declare(symbol)
        if duplicate is not None:
            self.errors.append(
                f"line {symbol.line}: duplicate definition of identifier '{symbol.name}' "
                f"in scope '{self.table.current.name}', first defined at line {duplicate.line}"
            )

    def error(self, token: Token, message: str) -> None:
        self.errors.append(f"line {token.line}: {message}")

    @staticmethod
    def to_int(token: Token) -> int | None:
        try:
            return int(token.sem)
        except (TypeError, ValueError):
            return None


def same_type(left: TypeInfo, right: TypeInfo) -> bool:
    if left.kind == "unknown" or right.kind == "unknown":
        return True
    if left.kind != right.kind:
        return False
    if left.kind in {"integer", "char", "bool"}:
        return True
    if left.kind == "array":
        return (
            left.low == right.low
            and left.high == right.high
            and left.element is not None
            and right.element is not None
            and same_type(left.element, right.element)
        )
    if left.kind == "record":
        if left.fields.keys() != right.fields.keys():
            return False
        return all(same_type(left.fields[name], right.fields[name]) for name in left.fields)
    return True


def format_semantic_result(analyzer: SNLSemanticAnalyzer) -> str:
    lines = ["Semantic Errors"]
    if analyzer.errors:
        lines.extend(analyzer.errors)
    else:
        lines.append("No semantic errors.")

    lines.append("")
    lines.append("Symbol Tables")
    for scope in analyzer.table.scopes:
        parent = "-" if scope.parent is None else str(scope.parent)
        lines.append(f"Scope #{scope.number} {scope.name} level={scope.level} parent={parent}")
        if not scope.symbols:
            lines.append("  <empty>")
            continue
        lines.append("  Kind       Name             Type                                      Other")
        lines.append("  ---------  ---------------  ----------------------------------------  ----------------")
        for symbol in scope.symbols.values():
            lines.append(
                f"  {symbol.kind:<9}  {symbol.name:<15}  "
                f"{symbol.type_display():<40}  {symbol.other_display()}"
            )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Analyze SNL token semantics and output semantic errors plus symbol tables."
    )
    parser.add_argument("tokens", type=Path, help="token file generated by snl_lexer.py")
    parser.add_argument("-o", "--output", type=Path, help="write semantic result to this file")
    args = parser.parse_args(argv)

    try:
        tokens = load_tokens(args.tokens)
        analyzer = SNLSemanticAnalyzer(tokens)
        analyzer.analyze()
        output = format_semantic_result(analyzer)
    except (OSError, SemanticError, json.JSONDecodeError) as exc:
        print(f"snl_semantic.py: {exc}", file=sys.stderr)
        return 2

    if args.output:
        args.output.write_text(output + "\n", encoding="utf-8")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
